#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
 @Author:      howardhhm
 @Email:       howardhhm@126.com
 @DateTime:    2017-03-18 09:51:16
 @Description: Description
'''

# import pip
import os
from subprocess import call
import sys

# call("pip list --outdated --format=columns", shell=True)

if (len(sys.argv) > 1 and sys.argv[1] == "--user"):
    cmdline = 'pip list --outdated --format=columns --user'
    updatestr = "pip install --upgrade --user "
else:
    cmdline = 'pip list --outdated --format=columns'
    updatestr = "pip install --upgrade "

packages = os.popen(cmdline).readlines()
outdated = []
for package in packages:
    print package.strip('\n')
    outdated.append(package.split(' ')[0])

outdated = outdated[2:]
if len(outdated) > 0:
    print
    # print outdated
    for dist in outdated:
        call(updatestr + dist, shell=True)
    # for dist in pip.get_installed_distributions():
    #     call(updatestr + dist.project_name, shell=True)
else:
    print "All packages are lastest!"
